// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChP9AhHP8LpHxt4rGwiV1mJD4evdD9_wE',
    appId: '1:463085592208:web:815566f21d947a3c7c4215',
    messagingSenderId: '463085592208',
    projectId: 'ala-ainy',
    authDomain: 'ala-ainy.firebaseapp.com',
    storageBucket: 'ala-ainy.firebasestorage.app',
    measurementId: 'G-8LFHR6GE9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMVLMHiftxL0CAus4OxSMEPbMkfabzSK0',
    appId: '1:463085592208:android:f40fcf57ff81403b7c4215',
    messagingSenderId: '463085592208',
    projectId: 'ala-ainy',
    storageBucket: 'ala-ainy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyfQaABCZIrYoCWbEqBP9KnRJQUFosSjg',
    appId: '1:463085592208:ios:cfb9bf589712fe767c4215',
    messagingSenderId: '463085592208',
    projectId: 'ala-ainy',
    storageBucket: 'ala-ainy.firebasestorage.app',
    iosBundleId: 'com.alaainy.alaAinyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyfQaABCZIrYoCWbEqBP9KnRJQUFosSjg',
    appId: '1:463085592208:ios:cfb9bf589712fe767c4215',
    messagingSenderId: '463085592208',
    projectId: 'ala-ainy',
    storageBucket: 'ala-ainy.firebasestorage.app',
    iosBundleId: 'com.alaainy.alaAinyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChP9AhHP8LpHxt4rGwiV1mJD4evdD9_wE',
    appId: '1:463085592208:web:8e9a5abb40c790db7c4215',
    messagingSenderId: '463085592208',
    projectId: 'ala-ainy',
    authDomain: 'ala-ainy.firebaseapp.com',
    storageBucket: 'ala-ainy.firebasestorage.app',
    measurementId: 'G-DY3CFG0SLD',
  );
}
